### ISSUE TITLE
Error object in callback is null

### ISSUE THREAD

**Issue by ryan-saffer** [AcuityScheduling/acuity-js#10]
When calling '/appointments/:id' with an invalid id, the error object is returned as the 'appointment', and the 'err' variable is set to null.

Here is my javascript code:
```
function updateAppointment() {
  var options = {
    method: 'PUT',
    body: {
      firstName: "updated first name"
    }
  }

  return new Promise((resolve, reject) => {
    acuity.request(`/appointments/invalid_id`, options, (err, _res, appointment) => {
      console.log(err) // output: null
      if (err) {
        // this code is never reached
        reject(err)
      }
      console.log(appointment) // output: { "status_code":404, "message":"Not Found", "error":"not_found" }
      resolve(appointment)
    })
}
```

Am I missing something, or is this broken?

**Comment by cesutherland** [comment]
Hey @ryan-saffer — you've got that right!  err will populate if there's been some error making the request, such as a network or other connection error.  Requests which are successfully made populate the response status code and the SDK parses any JSON response from the server, including for non-200 responses.

**Comment by ryan-saffer** [comment]
Hey @cesutherland, thanks for the response.

This design seems very strange to me, and I don't see why the error value in the callback doesn't wrap up both network/general errors along with acuity specific errors.

Since I am making these calls inside my own express app, I need to amend the code to look like:
```
return new Promise((resolve, reject) => {
  acuity.request(`/appointments/invalid_id`, options, (err, _res, appointment) => {
      if (err) reject(err)
      if (appointment.error) reject(appointment)

      resolve(appointment)
  })
}
```
But now that this is clear, I can at least work with it for now :)

On another note... any chance this npm package will get a @types package for TypeScript?

**Comment by cesutherland** [comment]
@ryan-saffer all clear!  Our library (more or less) is built on top request.js and matches that API pretty closely — so that's the underlying reason.

We don't have any plans for major improvements to our SDK at this time, any large future improvements would almost certainly include TS & types.  Appreciate the feedback!
