### ISSUE TITLE
Is there a way to set calendar availability?

### ISSUE THREAD

**Issue by HiccupinGminor** [AcuityScheduling/acuity-js#11]
The docs indicate that reading and verifying availability is allowed, but what about setting availability? Is that something that is possible through the public api?

**Comment by SudoPlz** [comment]
Hey there @HiccupinGminor, unfortunately no, there's no way to set availability through our public API.
We'll let our product team know that you're interested in that feature though - can't really make any promises, but if we do bake that into our API we'll let you know.

**Comment by samturner3** [comment]
Can just do this via a linked google calendar as there is apis to create events (block off times etc).
