### ISSUE TITLE
Finding the first most available appointment slot

### ISSUE THREAD

**Issue by pandu-supriyono** [AcuityScheduling/acuity-js#12]
Hi, firstly thanks for the API!

I have been thinking of improving the UX of my own implementation of a booking calendar by indicating when the next available appointment (date) is. 

Is there a smart way to go about finding this date? 
I can only think of some sort of (recursive) function similar to the pseudo code below:

1. Check if there are available appointments this month
2. While the available appointments array is empty, check if there are available appointments the next month
3. Return the available appointments array if the number of available appointments is one or more

I am afraid to get a 429 error which would make it quite unreliable if this function is run every time a user opens the calendar so I am thinking if it is a good idea to run a cron job or something of the like instead which saves this value elsewhere and have the client grab the first available appointment from there (accepting some margin of error).

I would appreciate any suggestions! Many thanks :)

**Comment by SudoPlz** [comment]
Hey there @pandu-supriyono 

I think your understanding of our api is really good, and I believe what you just suggested is the way to go.

Fetching availability for a month [using GET availability/dates](https://developers.acuityscheduling.com/reference#get-availability-dates) would probably be all you need.
Our [current enforced limitation](https://developers.acuityscheduling.com/reference#api-errors) would be: 

> 10 requests a second and 20 concurrent connections from an IP.

so assuming that you probably won't be needing crazy amounts of requests to find the next available date, I wouldn't really worry about 429s.

If it comes to that point, you can always add a delay between your requests to make sure you avoid getting rate limited.

**Comment by pandu-supriyono** [comment]
Hi @SudoPlz 

Fantastic, I'll give it a shot. I think I will implement some sort of simple caching system anyway since the first-most available appointments are usually many months ahead in this use case so I am okay with sacrificing accuracy for speed as far as UX is concerned.

Many thanks for your input! :)

**Comment by samturner3** [comment]
Yep this is the same approach I took, additionally:

- Save the next available appointment in redis (cache) 
- expire cache in 20 minutes, or at next appointment time if its sooner than 20 minutes.
- Invalidate the cache when any appointment is made/changed/cancelled 

It would be great however to have an endpoint in Acuity to just grab next appointment based on all or specific `appointment-types`

Will leave my (not super polished) code here incase it helps someone in future trying to achieve same thing.
```
const available_slots = async () => {

// Could make these dynamic from locations endpoint. (appointment-types)
  const locations = [
    { name: 'Location0', id: process.env.0_ID},
    { name: 'Location1', id: process.env.1_ID}
  ];

  logger.debug('Request received /availableSlots');
  
  let sortedArray = appCache.get( 'nextAppointments' );
  if ( sortedArray == undefined ){
    // handle expired/missing cache; fetch anew
    let resultArray = [];
    try {
      await Promise.all(locations.map(async location => {
        let dates = await (aucityApi.availability_dates(location.id, 'now'))
        if(!dates || !dates[0] || !dates[0].date) {
        // try next month
          dates = await aucityApi.availability_dates(location.id, '+1 month')
        }
        if(!dates || !dates[0] || !dates[0].date) {
          throw new Error('No dates found this or next month');
        }
  
        let times = await aucityApi.availability_times(location.id, dates[0].date);
        if(!times || !times[0] || !times[0].time) throw new Error('No times found');
  
        times.map(time => resultArray.push({time: time.time, location}));
        return times
      }))
      if(!resultArray || !resultArray[0] || !resultArray[0].time) throw new Error ('No times found in final array');
  
      logger.debug('resultArray:', resultArray);
  
      sortedArray = resultArray.sort((a,b) => new Moment(a.time) - new Moment(b.time));

      logger.debug('sortedArray:', sortedArray);
  
      if(!sortedArray || !sortedArray[0] || !sortedArray[0].time) {
        logger.error('Cannot save to cache, nothing in sortedArray');
        throw new Error ('Cannot save to cache, nothing in sortedArray');
      }
      // expire cache in 20 minutes, or at next appointment time if its sooner than 20 minutes
      if (Moment(sortedArray[0].time).isSameOrBefore(Moment().add(20, 'm'))) { // if next appointment is before next standard cache expire time
      // set expire time at next appointment time
        appCache.set( 'nextAppointments', sortedArray, Moment(sortedArray[0].time).diff(Moment(), 'seconds') );
      } else {
      // set expire in 20 minutes
        appCache.set( 'nextAppointments', sortedArray, 1200 );
      }
      // save to cache
      logger.info(`Saved request to cache. Expires ${Moment(appCache.getTtl( 'nextAppointments' )).format()} - ${Moment(appCache.getTtl( 'nextAppointments' )).fromNow()}`);
    
    
    } catch (error){      
      logger.error('thrown from Promise.all failed', error.message)
      throw error;
    }
      
  } else {
    logger.info(`Grabbed request from cache. Expires ${Moment(appCache.getTtl( 'nextAppointments' )).format()} - ${Moment(appCache.getTtl( 'nextAppointments' )).fromNow()}`);
  }
  logger.debug('Request resolved /availableSlots');
  return sortedArray;
};
```

Then usage. `/availableSlots` is endpoint the customer facing site calls.
```
const bookings = require('../controllers/bookings');
const webhookCallbacks = require('../controllers/webhookCallbacks');

router.get('/availableSlots', cors(), async (req, res, next) => {
  try {
    const availableSlots = await bookings.available_slots();
    res.status(200).send(availableSlots);
  } catch (error) {
    next(error)
  }
})
```
Webhook setup on Acuity to invalidate cache on appointment change (as the current cached next appointment available may no longer be available. Could maybe make this smarter to check it it was indeed the next available appointment that was changed.

```
// Sent from Acuity service when a booking was either scheduled rescheduled canceled changed or order.completed
router.post('/webhook-callback', cors(), async (req, res, next) => {
  const resultMessage = await webhookCallbacks.booking_changed();
  res.status(200).send(resultMessage);
})
```
```
const booking_changed = async () => {
  return new Promise((resolve, reject) => {
    logger.debug('Request received /webhook-callback');
    let value;
    try {
      value = appCache.del( 'nextAppointments' );
    } catch (error){      
      logger.error(error)
      reject(error)
    }
    logger.info(`Deleted ${value} keys from cache`);
    logger.debug('Request resolved /webhook-callback');
    resolve(`Deleted ${value} keys from cache`);
  })
};
```
