### ISSUE TITLE
NPM package "request" is deprecated

### ISSUE THREAD

**Issue by djr-jsr** [AcuityScheduling/acuity-js#13]
Can we move to some newer package like "axios"?

**Comment by ghost** [comment]
Is anything going to be done about it?

**Comment by cesutherland** [comment]
Hey folks, we are not actively developing our NPM package.

Since our package is only a thin wrapper around request, I recommend using `axios` directly today.

Here's an example for passing the access token:

```
axios.get("https://acuityscheduling.com/api/v1/appointments", {
  headers: {
    Authorization : `Bearer ${accessToken}`
  }
});
```
