### ISSUE TITLE
Please add a demo config into examples

### ISSUE THREAD

**Issue by n-lavrenko** [AcuityScheduling/acuity-js#5]
```
PORT=8000 node examples/create-appointment/index.js
module.js:472
    throw err;
    ^

Error: Cannot find module '../config'
```

Yes, I know that I can create it, but... It will be good for new devs.
Thanks

**Comment by cesutherland** [comment]
Hey there, thanks for the feedback!

I did go in and add a `config.sample.json` in the `examples` directory to give folks something to go off of.  Cheers!

**Comment by n-lavrenko** [comment]
@cesutherland Thanks! Great.
