### ISSUE TITLE
Support recurring events

### ISSUE THREAD

**Issue by JulianJorgensen** [AcuityScheduling/acuity-js#6]
It currently doesn't seem intuitive how to approach recurring appointments. Should I utilize `Blocks` or simply create a batch of appointments on one go?

**Comment by SudoPlz** [comment]
Hey there Julian,

to create recurring appointments you can just use the [post /appointments](https://developers.acuityscheduling.com/v1.1/reference#post-appointments) endpoint multiple times. Once for each recurring appointment.

Below I have pasted an example request:

```
POST "https://acuityscheduling.com/api/v1/appointments"

{
  "datetime": "2016-02-03T14:00:00-0800",
  "appointmentTypeID": 1,
  "firstName": "Bob",
  "lastName": "McTest",
  "email": "bob.mctest@example.com",
  "certificate": "ABC123",
  "fields": [
    {"id": 1, "value": "Party time!"}
  ]
}
```

**Comment by cesutherland** [comment]
@JulianJorgensen if you have any other questions on our API, you can reach out to us here: https://developers.acuityscheduling.com/docs/support

We'll be happy to help!

**Comment by kozak-codes** [comment]
@cesutherland This has the unfortunate side effect of sending multiple notifications per appointment. Is there any way to replicate the behaviour from the application, where only one email is sent with all of the ICS files in it?

**Comment by cesutherland** [comment]
> @cesutherland This has the unfortunate side effect of sending multiple notifications per appointment. Is there any way to replicate the behaviour from the application, where only one email is sent with all of the ICS files in it?

Hey there @KleptoKat !  Currently it's undocumented, but could you try posting your multiple appointments as an array to the `/appointments` endpoint?  I think that ought to do what you're looking for.

**Comment by kozak-codes** [comment]
> > @cesutherland This has the unfortunate side effect of sending multiple notifications per appointment. Is there any way to replicate the behaviour from the application, where only one email is sent with all of the ICS files in it?
> 
> Hey there @KleptoKat ! Currently it's undocumented, but could you try posting your multiple appointments as an array to the `/appointments` endpoint? I think that ought to do what you're looking for.

This works perfectly and is what I was going for, thank you!
